### PR TITLE
Corrected SQL and added JSON lexer.  Corrected fold coloring.

### PR DESCRIPTION
**Pull request by jpdillingham**

### CODE REVIEW

**Comment by Nidre** [comment]
@jpdillingham 

Sorry for the late reply. I will check this as soon as I can. Can you promptly explain what exactly have you fixed so I will where exactly to look! :)

Thanks!

**Comment by Ludomancer** [comment]
@jpdillingham  I will check this and include it as soon as I can! Thanks for the Json addition!

**Comment by jpdillingham** [comment]
Thanks! For whatever reason Visual Studio uses different coloring for some of the SQL elements.  I've updated the colors to match VS exactly.  I also added the "COMMENT DOC" and "COMMENT LINE DOC" to handle multi-line comments.

**Comment by Ludomancer** [comment]
@jpdillingham 

I've promptly checked the changes and have some questions about some of the changes. Would be happy to merge the request once I'm clear about those :)

**Smalltalk**
- on line 559 under Smalltalk "bool long int char"  are added as "BOOL" keyword, instead they should have been categorized under "VARIABLE".
- and on 558 "if else for while" are under "BINARY", not sure how exactly Lexer categorizes things, but wouldn't they better fit under "KEYWORD" ? Let me know what do you think?

However I'vent used Smalltalk my self. If there is a reasonable explanation about why they are included under "BOOL" instead of "VARIABLE" please let me know.

**Innosetup**
- Similarly on line 685 under InnoSetup "bool long int char" are added as "PREPROCESSOR" instead of "VARIABLE"
- and "if else for while" might seem more appropriate being categorized under "KEYWORD" similar to line 558.

**CMake**
- Not sure but on line 702 is there a reason why did you put "bool long int char" under "PARAMETER" instead of "VARIABLE" ?

Let me know what do you think?

**Comment by jpdillingham** [comment]
Those additions were made by the latest version of NPP automatically.  I'm assuming it was done to support new functionality but I'm not entirely sure.

**Pull request merged**
